Move `resource_usage` to roxy and use roxy's `reboot`
petabi/oinq pull request #18
Opened 2022-11-12 13:57 UTC by sehkone

This PR is dependent on [roxy's](https://github.com/aicers/roxy/pull/84). This is referring to the branch of the roxy's PR but will be changed to refer to the roxy main when it is merged into the main.

2022-11-13 11:28 UTC, sehkone commented
@msk ,

When do users need to call `request::handle_resource_usage`?

2022-11-14 22:18 UTC, msk commented
Pending until aicers/roxy#86 is resolved and all the other projects (piglet, reconverge, and hog) have been converted to use roxy.

2022-11-16 12:37 UTC, sehkone commented
> Pending until [aicers/roxy#86](https://github.com/aicers/roxy/issues/86) is resolved and all the other projects (piglet, reconverge, and hog) have been converted to use roxy.

Since [aicers/roxy#86](https://github.com/aicers/roxy/issues/86) has been resolved and the other projects need this version of oinq to implement their using roxy, @msk, would you proceed this?

2022-11-16 17:54 UTC, msk requested changes

2022-11-16 17:54 UTC, msk commented on .github/workflows/ci.yml
> -        os: [ubuntu-latest, macOS-latest, windows-latest]
What build/test error do you get on Windows?

2022-11-16 17:54 UTC, msk commented on src/request.rs
> +use roxy::ResourceUsage;
Since `ResouceUsage` is a part of the API, it should be defined in oinq.

2022-11-16 17:54 UTC, msk commented on Cargo.toml
> +rust-version = "1.65"
Does oinq use anything unavailable in 1.64?

2022-11-17 00:19 UTC, msk approved these changes

2022-11-17 00:20 UTC, merged